name = "Eternal Edge"
author = "Latipun"
version = "1.0.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8281460e9ae3be0a0b3dac19fadfedb77d5d4cfa87b21cb2d35a982cfea4c37"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2"]
datapack-folder = "config/paxi/datapacks"
