name = "Eternal Edge"
author = "Latipun"
version = "1.0.0-beta.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b52e144063bf74b5e9db9639fdf627fa0d4131b788f74a9eada42b73bababd3f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2"]
datapack-folder = "config/paxi/datapacks"
