name = "Eternal Edge"
author = "Latipun"
version = "1.0.0-beta.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cc4e9810b6f0347bf9ea4ad6e3f0017fcd4af4209c7c93837bd344081b1b843"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2"]
datapack-folder = "config/paxi/datapacks"
